server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://seya.synology.me:23306/q-note?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: mariadb
    password: mariadb
#    username: lgm1995
#    password: 0528

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache
  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace  # query의 ?에 어떤 값이 들어가는지 추적할 수 있는 설정입니다. TRACE Log에 값을 보여줍니다.

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 752014485622-eli6j1lu89g3p9r8nr595m9brpoq2dd7.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

          facebook:
            client-id: 829322704892779
            client-secret: 23b84e9669d0b348f9f9aea361e92ea5
            scope:
            - email
            - public_profile


          # ???? OAuth2.0 ?? ????? ???? provider ??? ????.
          # ????? ???, ?? ???? ??? ????.
          naver:
            client-id: VgWbni1smPfys8_01zSL
            client-secret: UrtKRI99MS
            scope:
              - name
              - email
              - profile_image
            client-name: Naver # ????? ??? ?? ????? ???? ?????.
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # ????? json? response ???? ????.
